### PR TITLE
Update README.md installation section

### PR DESCRIPTION
**Pull request by kakaska**

### CODE REVIEW

**Comment by kakaska** [comment]
@NicolasDorier could you please enable issues on this repo?

**Comment by NicolasDorier** [comment]
I need to contact github. The problem is that this is a fork.

**Comment by NicolasDorier** [comment]
I sent them a mail, let's see what happen.

**Comment by kakaska** [comment]
I think you can enable it in the repo settings -> Options tab -> Features

**Comment by NicolasDorier** [comment]
@kakaska I contacted github, they will put this repo back in "normal mode" so we are not a fork of Bitpay anymore.

**Comment by NicolasDorier** [comment]
@kakaska you are right, I just activated the issues. Though it is good we are not parent anymore then as we can finally search through the source code.

**Pull request merged**
